[package]
name = "one-line-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
clap = { version = "4.5.21", features = ["derive"] }
